import { BinAritOperator, BinCmdOperator, BinTestOperator, CaseOperator, GlobOperator, I_Expansion, I_Pos, I_Replace, I_Slice, IArithmCmd, IArithmExp, IArithmExpr, IArrayElem, IArrayExpr, IAssign, IBinaryArithm, IBinaryCmd, IBinaryTest, IBlock, IBraceExp, ICallExpr, ICaseClause, ICaseItem, ICmdSubst, ICommand, IComment, ICoprocClause, ICStyleLoop, IDblQuoted, IDeclClause, IExtGlob, IFile, IForClause, IFuncDecl, IIfClause, ILetClause, ILit, ILoop, IParamExp, IParenArithm, IParenTest, IProcSubst, IRedirect, ISglQuoted, IStmt, IStmtList, ISubshell, ITestClause, ITestExpr, ITimeClause, IUnaryArithm, IUnaryTest, IWhileClause, IWord, IWordIter, IWordPart, ParNamesOperator, ProcOperator, RedirOperator, UnAritOperator, UnTestOperator } from "./ParserTypes";
export declare function prepArithmCmd(arithmcmd: IArithmCmd | null): string[];
export declare function prepArithmExp(arithmexp: IArithmExp | null): string[];
export declare function prepArithmExpr(arithmexpr: IArithmExpr | null): string[];
export declare function prepArrayElem(arrayelem: IArrayElem | null): string[];
export declare function prepArrayExpr(arrayexpr: IArrayExpr | null): string[];
export declare function prepAssign(assign: IAssign | null): string[];
export declare function prepBinaryArithm(binaryarithm: IBinaryArithm | null): string[];
export declare function prepBinaryCmd(binarycmd: IBinaryCmd | null): string[];
export declare function prepBinaryTest(binarytest: IBinaryTest | null): string[];
export declare function prepBlock(block: IBlock | null): string[];
export declare function prepBraceExp(braceexp: IBraceExp | null): string[];
export declare function prepCStyleLoop(cstyleloop: ICStyleLoop | null): string[];
export declare function prepCallExpr(callexpr: ICallExpr | null): string[];
export declare function prepCaseClause(caseclause: ICaseClause | null): string[];
export declare function prepCaseItem(caseitem: ICaseItem | null): string[];
export declare function prepCmdSubst(cmdsubst: ICmdSubst | null): string[];
export declare function prepCommand(command: ICommand | null): string[];
export declare function prepComment(comment: IComment | null): string[];
export declare function prepCoprocClause(coprocclause: ICoprocClause | null): string[];
export declare function prepDblQuoted(dblquoted: IDblQuoted | null): string[];
export declare function prepDeclClause(declclause: IDeclClause | null): string[];
export declare function prepExtGlob(extglob: IExtGlob | null): string[];
export declare function prepFile(file: IFile | null): string[];
export declare function prepForClause(forclause: IForClause | null): string[];
export declare function prepFuncDecl(funcdecl: IFuncDecl | null): string[];
export declare function prepIfClause(ifclause: IIfClause | null): string[];
export declare function prepLetClause(letclause: ILetClause | null): string[];
export declare function prepLit(lit: ILit | null): string[];
export declare function prepLoop(loop: ILoop | null): string[];
export declare function prepParamExp(paramexp: IParamExp | null): string[];
export declare function prepParenArithm(parenarithm: IParenArithm | null): string[];
export declare function prepParenTest(parentest: IParenTest | null): string[];
export declare function prepProcSubst(procsubst: IProcSubst | null): string[];
export declare function prepRedirect(redirect: IRedirect | null): string[];
export declare function prepSglQuoted(sglquoted: ISglQuoted | null): string[];
export declare function prepStmt(stmt: IStmt | null): string[];
export declare function prepStmtList(stmtlist: IStmtList | null): string[];
export declare function prepSubshell(subshell: ISubshell | null): string[];
export declare function prepTestClause(testclause: ITestClause | null): string[];
export declare function prepTestExpr(testexpr: ITestExpr | null): string[];
export declare function prepTimeClause(timeclause: ITimeClause | null): string[];
export declare function prepUnaryArithm(unaryarithm: IUnaryArithm | null): string[];
export declare function prepUnaryTest(unarytest: IUnaryTest | null): string[];
export declare function prepWhileClause(whileclause: IWhileClause | null): string[];
export declare function prepWord(word: IWord | null): string[];
export declare function prepWordIter(worditer: IWordIter | null): string[];
export declare function prepWordPart(wordpart: IWordPart | null): string[];
export declare function prepArithmExprs(arithmexprs: IArithmExpr[] | null): string[];
export declare function prepArrayElems(arrayelems: IArrayElem[] | null): string[];
export declare function prepAssigns(assigns: IAssign[] | null): string[];
export declare function prepCaseItems(caseitems: ICaseItem[] | null): string[];
export declare function prepComments(comments: IComment[] | null): string[];
export declare function prepRedirects(redirects: IRedirect[] | null): string[];
export declare function prepStmts(stmts: IStmt[] | null): string[];
export declare function prepWords(words: IWord[] | null): string[];
export declare function prepWordParts(wordparts: IWordPart[] | null): string[];
export declare function prep(a: null): null;
export declare function prepBinAritOperator(aBinaritoperator: BinAritOperator | null): BinAritOperator | null;
export declare function prepBinCmdOperator(aBincmdoperator: BinCmdOperator | null): BinCmdOperator | null;
export declare function prepBinTestOperator(aBintestoperator: BinTestOperator | null): BinTestOperator | null;
export declare function prepboolean(aBoolean: boolean | null): boolean | null;
export declare function prepCaseOperator(aCaseoperator: CaseOperator | null): CaseOperator | null;
export declare function prepGlobOperator(aGloboperator: GlobOperator | null): GlobOperator | null;
export declare function prepExpansion(aExpansion: I_Expansion | null): I_Expansion | null;
export declare function prepPos(aPos: I_Pos | null): I_Pos | null;
export declare function prepReplace(aReplace: I_Replace | null): I_Replace | null;
export declare function prepSlice(aSlice: I_Slice | null): I_Slice | null;
export declare function prepParNamesOperator(aParnamesoperator: ParNamesOperator | null): ParNamesOperator | null;
export declare function prepProcOperator(aProcoperator: ProcOperator | null): ProcOperator | null;
export declare function prepRedirOperator(aRediroperator: RedirOperator | null): RedirOperator | null;
export declare function prepstring(aString: string | null): string | null;
export declare function prepUnAritOperator(aUnaritoperator: UnAritOperator | null): UnAritOperator | null;
export declare function prepUnTestOperator(aUntestoperator: UnTestOperator | null): UnTestOperator | null;
//# sourceMappingURL=ParserPrep.d.ts.map