/** Declaration file generated by dts-gen */

export = mvdan_sh;

declare const mvdan_sh: {
    syntax: {
        DebugPrint: any;
        KeepComments: any;
        LangBash: number;
        LangMirBSDKorn: number;
        LangPOSIX: number;
        NewParser: any;
        NewPrinter: any;
        NodeType: any;
        StopAt: any;
        Variant: any;
        Walk: any;
    };
};

